[window]
dimensions = { columns = 80, lines = 24}
dynamic_title = true

[scrolling]
history = 10000

[font]
normal = {family = "Monospace", style = "Regular"}
size = 12

[colors.primary]
background = "#000000"

