# lazygit configuration
# Docs: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

git:
  pagers:
    - pager: delta --dark --tabs=2 --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
